version: 2
updates:
    - package-ecosystem: composer
      directory: "/"
      schedule:
          interval: weekly
      open-pull-requests-limit: 5
    - package-ecosystem: docker
      directory: "/"
      schedule:
          interval: monthly
      open-pull-requests-limit: 5