framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    #http_method_override: true

    default_locale: en

    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - en

    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax

    #esi: true
    #fragments: true
    php_errors:
        log: true

    router:
        utf8: true
