monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event", "!router","!doctrine","!request","!security"]
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!router", "!doctrine", "!console"]
