services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Api\Infrastructure\:
        resource: '../../../../src/Api/Infrastructure/'
        exclude: '../../../../src/Api/Infrastructure/{Symfony}'

    Api\Infrastructure\Symfony\Controller\:
        resource: '../../../../src/Api/Infrastructure/Symfony/Controller/'
        tags: [ 'controller.service_arguments' ]

    Api\Infrastructure\Symfony\Console\:
        resource: '../../../../src/Api/Infrastructure/Symfony/Console/'