services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Symfony\Component\Serializer\Normalizer\PropertyNormalizer:
        class: Symfony\Component\Serializer\Normalizer\PropertyNormalizer
        public: false
        arguments:
            - '@serializer.mapping.class_metadata_factory'
            - '@serializer.name_converter.camel_case_to_snake_case'
        tags:
            - { name: 'serializer.normalizer' }

    Symfony\Component\Serializer\Normalizer\DateTimeNormalizer:
        class: Symfony\Component\Serializer\Normalizer\DateTimeNormalizer
        public: false
        tags:
            - { name: 'serializer.normalizer' }