services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Shared\Infrastructure\:
        resource: '../../../../src/Shared/Infrastructure/'
        exclude: '../../../../src/Shared/Infrastructure/{Symfony,Persistence}'

    Shared\Infrastructure\Symfony\Controller\:
        resource: '../../../../src/Shared/Infrastructure/Symfony/Controller'
        tags: [ 'controller.service_arguments' ]


    # Messenger Bus
    Shared\Infrastructure\Symfony\MessageBus\MessageBus:
        class: Shared\Infrastructure\Symfony\MessageBus\MessageBus

    Shared\Infrastructure\Symfony\MessageBus\MessageBusHandler:
        class: Shared\Infrastructure\Symfony\MessageBus\MessageBusHandler
        calls:
            - method: registerAll
              arguments:
                  - [
                        '@Api\Application\Notifications\Subscribe\NotificationCreatedSubscriber'
                    ]

    symfony_uuid_generator:
        class: Shared\Infrastructure\Symfony\UidGenerator\SymfonyUuidGenerator

imports:
    - { resource: event_listeners.yaml }
    - { resource: serializers.yaml }