services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Shared\Domain\:
        resource: '../../../../src/Shared/Domain/'

    Shared\Domain\UuidGenerator: '@symfony_uuid_generator'
    Shared\Domain\Logger: '@Shared\Infrastructure\Logging\MonologLogger'