# / routes

get_index:
    path: /
    controller: Shared\Infrastructure\Symfony\Controller\IndexGetController
    methods: GET

get_health_check:
    path: /health_check
    controller: Shared\Infrastructure\Symfony\Controller\HealthCheckGetController
    methods: GET