services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    # Repositories
    Api\Domain\Model\Note\NoteRepository: '@Api\Infrastructure\Persistence\InMemory\InMemoryNoteRepository'